// frontend/src/modules/connect-workshop/connect-workshop.view.ts - Refactored with PageManager
import { ConnectWorkshopModule } from './connect-workshop.module';
import { ConnectWorkshopPageManager } from './pages';
import { createModuleMenu } from '../../components/connect-menu';

export class ConnectWorkshopView {
  private currentSection: string = 'requests';
  private currentMethod: string = 'search';
  private pageManager: ConnectWorkshopPageManager;

  constructor(_module: ConnectWorkshopModule) {
    // Initialize page manager
    this.pageManager = new ConnectWorkshopPageManager();
  }

  render(): HTMLElement {
    const container = document.createElement('div');
    container.className = 'connect-workshop-compact';
    
    // Update top-bar elements
    this.updateTopBarElements();
    
    // Create new layout with menu and content
    container.innerHTML = `
      <div class="module-with-menu">
        <div id="connect-workshop-menu-container">
          <!-- Menu will be generated by MenuManager -->
        </div>
        <div class="module-main-content" id="connect-workshop-content">
          <!-- Content will be loaded by PageManager -->
        </div>
      </div>
    `;

    // Initialize page manager with content container
    const contentContainer = container.querySelector('#connect-workshop-content') as HTMLElement;
    if (contentContainer) {
      this.pageManager.initialize(contentContainer);
    }

    // Create module menu using MenuManager
    const menuContainer = container.querySelector('#connect-workshop-menu-container') as HTMLElement;
    if (menuContainer) {
      createModuleMenu('connect-workshop', menuContainer, {
        onItemClick: (data) => {
          const { item, column } = data;
          console.log(`🔧 ConnectWorkshop Menu: Click on ${item.id} in column ${column.id}`);
          
          // Update current section and method based on menu click
          if (item.section) {
            this.currentSection = item.section;
            console.log(`🔧 ConnectWorkshop: Section changed to ${this.currentSection}`);
          }
          if (item.method) {
            this.currentMethod = item.method;
            console.log(`🔧 ConnectWorkshop: Method changed to ${this.currentMethod}`);
          }
          
          // Load the page for current selection
          this.loadCurrentPage();
        }
      });
    }
    
    // Add custom styles
    this.addCustomStyles();
    
    // Load initial page based on current state
    this.loadCurrentPage();
    
    return container;
  }

  /**
   * Load current page based on section and method
   */
  private loadCurrentPage(): void {
    console.log(`🔧 ConnectWorkshop: Loading page ${this.currentSection}-${this.currentMethod}`);
    this.pageManager.loadPage(this.currentSection, this.currentMethod);
  }

  private updateTopBarElements(): void {
    // Update top-bar submenu
    const submenu = document.getElementById('top-bar-submenu');
    if (submenu) submenu.textContent = '🔧 Workshop Client';
    
    // Update top-bar section title
    const sectionTitle = document.getElementById('top-bar-section-title');
    if (sectionTitle) {
      const sectionLabel = this.currentSection === 'requests' ? 'Zgłoszenia' :
                          this.currentSection === 'services' ? 'Serwisy' :
                          this.currentSection === 'transport' ? 'Transport' :
                          this.currentSection === 'dispositions' ? 'Dyspozycje' : 'Workshop';
      sectionTitle.textContent = `ConnectWorkshop - ${sectionLabel}`;
    }
  }

  private addCustomStyles(): void {
    // Check if styles already added
    if (document.getElementById('connect-workshop-compact-styles')) {
      return;
    }

    const style = document.createElement('style');
    style.id = 'connect-workshop-compact-styles';
    style.textContent = this.getCompactStyles();
    document.head.appendChild(style);
  }

  private getCompactStyles(): string {
    return `
      .connect-workshop-compact {
        height: 100%;
        width: 100%;
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      }

      .module-with-menu {
        display: flex;
        height: 100%;
        width: 100%;
      }
      
      #connect-workshop-menu-container {
        width: 280px;
        background: #f8f9fa;
        border-right: 1px solid #e9ecef;
        overflow-y: auto;
      }
      
      .module-main-content {
        flex: 1;
        overflow-y: auto;
        background: white;
      }
    `;
  }
}
