# Development overrides - no Redis needed for simple app

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public:ro
      - ./frontend/index.html:/app/index.html:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8101
      - VITE_HMR_PORT=24678
    ports:
      - "8200:3000"
      - "24678:24678"  # HMR port
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 15s      # Częstsze sprawdzanie
      timeout: 5s        # Krótszy timeout
      retries: 2         # Mniej prób
      start_period: 20s  # Krótszy start period

  backend:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
    volumes:
      - ./backend:/app:ro
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
