// frontend/src/modules/connect-reports/pages/export-custom.page.ts
export class ExportCustomPage {
  static getContent(): string {
    return `<div class="page-content"><div class="page-header"><h2>📤 Export - Niestandardowy</h2><p>Eksportuj raporty dla dowolnego zakresu</p></div><div class="date-range-export"><div class="date-input"><label>Data od:</label><input type="date" value="2025-01-01" class="input-date"></div><div class="date-input"><label>Data do:</label><input type="date" value="2025-10-11" class="input-date"></div></div><div class="export-options"><h3>📋 Wybierz format eksportu</h3><div class="format-buttons"><button class="format-btn">📄 PDF</button><button class="format-btn">📊 Excel</button><button class="format-btn">📋 CSV</button><button class="format-btn">📧 Email</button></div></div><div class="export-filters"><h3>🔍 Dodatkowe filtry</h3><label><input type="checkbox" checked> Wykonane</label><label><input type="checkbox" checked> Zaplanowane</label><label><input type="checkbox"> Opóźnione</label></div><button class="btn-export">📤 Eksportuj raport niestandardowy</button></div>`;
  }
  static getStyles(): string {
    return `.page-content{padding:20px;max-width:800px;margin:0 auto}.page-header h2{color:#333;font-size:24px;margin-bottom:5px}.date-range-export{display:flex;gap:15px;padding:20px;background:white;border-radius:8px;margin-bottom:20px}.date-input{flex:1}.date-input label{display:block;margin-bottom:5px;font-weight:600;font-size:13px}.input-date{width:100%;padding:10px;border:1px solid #ddd;border-radius:6px}.export-options{background:white;padding:20px;border-radius:8px;margin-bottom:20px}.export-options h3{margin:0 0 15px 0}.format-buttons{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.format-btn{padding:15px;background:#f8f9fa;border:2px solid #dee2e6;border-radius:6px;cursor:pointer;font-size:14px;font-weight:600}.format-btn:hover{background:#007bff;color:white;border-color:#007bff}.export-filters{background:white;padding:20px;border-radius:8px;margin-bottom:20px}.export-filters h3{margin:0 0 15px 0}.export-filters label{display:block;margin-bottom:10px}.btn-export{width:100%;padding:12px;background:#28a745;color:white;border:none;border-radius:6px;cursor:pointer;font-weight:600;font-size:15px}`;
  }
}
