// frontend/src/modules/connect-manager/connect-manager.view.ts - Refactored with PageManager
import { ConnectManagerPageManager } from './pages';
import { createModuleMenu } from '../../components/connect-menu';

export class ConnectManagerView {
  private currentSection: string = 'scenarios';
  private pageManager: ConnectManagerPageManager;

  constructor() {
    this.pageManager = new ConnectManagerPageManager();
  }

  render(): HTMLElement {
    const container = document.createElement('div');
    container.className = 'connect-manager-compact';
    
    // Update top-bar elements
    this.updateTopBarElements();
    
    // Create layout with menu and content
    container.innerHTML = `
      <div class="module-with-menu">
        <div id="connect-manager-menu-container">
          <!-- Menu will be generated by MenuManager -->
        </div>
        <div class="module-main-content" id="connect-manager-content">
          <!-- Content will be loaded by PageManager -->
        </div>
      </div>
    `;
    
    // Initialize page manager
    const contentContainer = container.querySelector('#connect-manager-content') as HTMLElement;
    if (contentContainer) {
      this.pageManager.initialize(contentContainer);
    }
    
    // Create module menu using MenuManager
    const menuContainer = container.querySelector('#connect-manager-menu-container') as HTMLElement;
    if (menuContainer) {
      createModuleMenu('connect-manager', menuContainer, {
        onItemClick: (data) => {
          const { item } = data;
          console.log(`⚙️ ConnectManager Menu: Click on ${item.id}`);
          
          // ConnectManager has only one column, so item.id is the section
          this.currentSection = item.id;
          console.log(`⚙️ ConnectManager: Section changed to ${this.currentSection}`);
          this.updateTopBarElements();
          this.loadCurrentPage();
        }
      });
    }
    
    // Add custom styles
    this.addCustomStyles();
    
    // Load initial page
    this.loadCurrentPage();
    
    return container;
  }

  /**
   * Load current page based on section
   */
  private loadCurrentPage(): void {
    console.log(`⚙️ ConnectManager: Loading page ${this.currentSection}`);
    this.pageManager.loadPage(this.currentSection);
  }

  private updateTopBarElements(): void {
    // Update top-bar submenu
    const submenu = document.getElementById('top-bar-submenu');
    if (submenu) submenu.textContent = '⚙️ Test Manager';
    
    // Update top-bar section title
    const sectionTitle = document.getElementById('top-bar-section-title');
    if (sectionTitle) {
      const sectionLabel = this.getSectionDisplayName(this.currentSection);
      sectionTitle.textContent = `ConnectManager - ${sectionLabel}`;
    }
  }

  private getSectionDisplayName(section: string): string {
    const names: Record<string, string> = {
      'scenarios': 'Scenariusze',
      'activities': 'Czynności',
      'test-types': 'Rodzaj Testu'
    };
    return names[section] || 'Manager';
  }

  private addCustomStyles(): void {
    // Check if styles already added
    if (document.getElementById('connect-manager-compact-styles')) {
      return;
    }

    const style = document.createElement('style');
    style.id = 'connect-manager-compact-styles';
    style.textContent = this.getCompactStyles();
    document.head.appendChild(style);
  }

  private getCompactStyles(): string {
    return `
      .connect-manager-compact {
        height: 100%;
        width: 100%;
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      }

      .module-with-menu {
        display: flex;
        height: 100%;
        width: 100%;
      }
      
      #connect-manager-menu-container {
        width: 280px;
        background: #f8f9fa;
        border-right: 1px solid #e9ecef;
        overflow-y: auto;
      }
      
      .module-main-content {
        flex: 1;
        overflow-y: auto;
        background: white;
      }
    `;
  }
}
